name: TurnoFacil CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar entorno de Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Verificar formato y estilo (Lint)
      run: go fmt ./...

    - name: Ejecutar Tests Unitarios con Mocks
      run: go test -v -cover -coverprofile=coverage.out ./...
    - name: Verificar Compilación (Build)
      run: go build -v ./cmd/api/main.go